### ISSUE TITLE
Allow new environment variables during push

### ISSUE THREAD

**Issue by gologic-ben** [emerald-squad/cf-blue-green-resource#1]
Hi,
Can you provide a way to add environment variables during push operation like the official "CF" resource (https://github.com/concourse/cf-resource) ?

**Pipeline example** 
```
params:
      manifest: build-output/manifest.yml
      environment_variables:
        key: value
        key2: value2
```

**Comment by ukabu** [comment]
In most cases, it is better to put the environment variables inside the `manifest.yml`.

I do see some use cases where this could be useful, credentials for example:
```
params
  manifest: build-output/manifest.yml
  env:
    mysecret: ((mysecret))
```
